global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: app
    static_configs:
      - targets: ["app-exporter:4748"]
    metrics_path: /v1/prometheus/

  - job_name: node
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: mongodb
    static_configs:
      - targets: ["mongodb-exporter:9216"]
